;****** ASSEMBLY PROGRAM *******
;PACKED TO UNPACKED (16 DIGITS)
;AUTHOR : VIPIN KUMAR (ROLL NO. 44)

DATA SEGMENT
	PACKED DB 22H,43H,65H,87H,78H,56H,34H,12H	    ; PACKED BCD 16 DIGIT NUMBER 
	UNPACKED DB 16 DUP(?)	  	                    ; UNPACKED BCD NUMBER  
DATA ENDS

CODE SEGMENT
	ASSUME DS:DATA,CS:CODE

	START:
		MOV AX,DATA
		MOV DS,AX
	
		MOV CX,8
		MOV SI,0
		MOV DI,0
		 
AGAIN:  MOV AX,0 
		MOV AL,PACKED+SI
		INC SI
		SHL AX,4
		SHR AL,4
		MOV UNPACKED+DI, AH
		INC DI
		MOV UNPACKED+DI,AL
		INC DI
		LOOP AGAIN
						
CODE ENDS
	END START

