DATA SEGMENT
    PACKED DB 23H
    UNPACKED DW 0H
    MASK1 DB 0FH
    MASK2 DB 0F0H
DATA ENDS

CODE SEGMENT
    ASSUME DS:DATA
    ASSUME CS:CODE
    
START:
        MOV AX,DATA
        MOV DS,AX
        
        MOV AX,0
        MOV AL,PACKED
        MOV AH,PACKED
        AND AL,MASK1
        AND AH,MASK2
        SHR AH,4
        MOV UNPACKED,AX
CODE ENDS
END START