;****** ASSEMBLY PROGRAM *******
;PACKED TO UNPACKED (16 DIGITS) (USING MASKING)
;AUTHOR : VIPIN KUMAR (ROLL NO. 44)

DATA SEGMENT
	PACKED DB 21H,43H,65H,87H,78H,56H,34H,12H	    ; PACKED BCD 16 DIGIT NUMBER 
	UNPACKED DB 16 DUP(?)	  	                    ; UNPACKED BCD NUMBER
	MASK1 DB 0FH                                    ; MASK1 : 00001111
    MASK2 DB 0F0H                                   ; MASK2 : 11110000
DATA ENDS

CODE SEGMENT
	ASSUME DS:DATA,CS:CODE

	START:
		MOV AX,DATA
		MOV DS,AX
	
		MOV CX,8
		MOV SI,0
		MOV DI,0
		 
AGAIN:  MOV AX,0 
		MOV AL,PACKED+SI
		MOV AH,PACKED+SI
		INC SI
		AND AL,MASK1
        AND AH,MASK2
        SHR AH,4
		MOV UNPACKED+DI, AH
		INC DI
		MOV UNPACKED+DI,AL
		INC DI
		LOOP AGAIN
						
CODE ENDS
	END START

