;***** ASSEMBLY LANGUAGE PROGRAM *****
;UNPACKED TO PACKED (16 DIGITS)
;AUTHOR : VIPIN KUMAR (44)

DATA SEGMENT
	UNPACKED DB 02H,03H,04H,05H,06H,07H,08H,09H,08H,07H,06H,05H,04H,03H,02H,01H	    ; 16 DIGIT UNPACKED BCD NUMBER  
	PACKED DB 8 DUP(?)	  	                                                        ; PACKED NUMBER
DATA ENDS

CODE SEGMENT
	ASSUME DS:DATA,CS:CODE

	START:	
		MOV AX,DATA
		MOV DS,AX
        MOV SI,0
        MOV DI,0
        MOV CX,8
        
AGAIN:	MOV AH,UNPACKED+SI
		INC SI
		MOV AL,UNPACKED+SI
		INC SI
		SHL AL,4
		SHR AX,4
		MOV PACKED+DI,AL
		INC DI
		LOOP AGAIN
				
CODE ENDS
	END START

 



 