DATA SEGMENT
    UNPACKED DW 040BH
    PACKED DB 0H
    MASK DB 00H
DATA ENDS

CODE SEGMENT
    ASSUME DS:DATA
    ASSUME CS:CODE
    
START:
        MOV AX,DATA
        MOV DS,AX
        
        MOV AX,UNPACKED
        ROR AH,4
        ADD AL,AH
        AND AH,MASK
        MOV PACKED,AL
CODE ENDS
END START
